branches:
 only:
  - master 

matrix:
  include:
   - os: linux
     language: generic
     env: TRAVIS_PYTHON_VERSION=3.6


install:
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes 
 - conda config --add channels omnia
 - conda config --add channels acellera
 - conda update --all -y
 - conda install conda-build -y

 - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION 
 - source activate travis-env
 - pwd
 - git describe --tags
 - export BUILD_VERSION=$(git describe --tags | sed 's/-/ /g' | awk '{print $1}')
 - export BUILD_NUMBER=$(git describe --tags | sed 's/-/ /g' | awk '{print $2}')
 # Always set it to 0 so we don't get a new release at every successful commit
 - export BUILD_NUMBER=0

 - conda build --python $TRAVIS_PYTHON_VERSION package/pdb2pqr/
 - conda install htmd-pdb2pqr --use-local

script:

after_success:
 - export PATH="$HOME/miniconda/bin:$PATH"
 - echo $PATH
 - anaconda -t $ANACONDA_TOKEN upload --force $HOME/miniconda/conda-bld/*/htmd-pdb2pqr-*.tar.bz2 -u acellera


