package:
  name:  htmd-pdb2pqr
  version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }} 


build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  noarch: python

source:
  git_url: https://github.com/tonigi/apbs-pdb2pqr
  git_rev: htmd-fixups


test:
    files:
        - 3PTB.pdb
    commands:
        - cat pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr
        - python pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr

 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - propka
   
about:
  home: http://www.poissonboltzmann.org/
  license: "BSD"
