package:
  name:  htmd-pdb2pqr
  version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }} 


build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

source:
  git_url: https://github.com/tonigi/apbs-pdb2pqr


test:
    files:
        - 3PTB.pdb
    commands:
        - pdb2pqr_cli --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr

 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - propka
   
about:
  home: http://www.poissonboltzmann.org/
  license: "BSD"
