package:
  name:  htmd-pdb2pqr
  version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}


build:
  noarch: python
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}
  entry_points:
    - pdb2pqr_cli = pdb2pqr.main:main

# Putting this in build.sh because the download is huge and --depth=1 saves a lot
# source:
#   git_url: https://github.com/tonigi/apbs-pdb2pqr
#   git_rev: htmd-fixups


test:
    files:
        - 3PTB.pdb
    commands:
        - pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr

 
requirements:
  build:
    - propka
    - python
    - setuptools
  run:
    - python
    - propka
   
about:
  home: http://www.poissonboltzmann.org/
  license: "BSD"
  description: Based on the official pdb2pqr, with patches to run on python 3.6 and 3.7 and use propka 3.1
